### PR TITLE
Handle a special-case shape issue for SubBB

### PR DESCRIPTION
**Pull request by Vimalakirti**
Our `SubBasicBlock` accept two inputs. When input[0].len()=1, we assumed that input[1].len() will not be 1. This PR included the case that we didn't consider before.

### CODE REVIEW

**Review by ddkang — COMMENTED** [review]
Can we test this?

**Comment by Vimalakirti** [comment]
> Can we test this?

we can test this with an ONNX that matches the description above

**Comment by liliatangxy** [comment]
Why can't we test this with a `testBasicBlock` test?

**Comment by Vimalakirti** [comment]
Thanks for the reviews, a new test case was added.

**Review by liliatangxy — APPROVED** [review]

**Review by ddkang — APPROVED** [review]

**Pull request merged**
