### PR TITLE
Handle special-case shape issues using Mul

### PR DESCRIPTION
**Pull request by Vimalakirti**
ONNX Mul accepts two inputs `a` and `b`, and returns `a*b`. It performs broadcasting for inputs when the shapes don't match.
We used MulBasicBlock when `a` and `b` are both 1-dimensional arrays and used MulScalarBasicBlock when `b` is a scalar. However, we didn't consider the case that `a` might also be a scalar in Mul and Where layers. 
This PR addressed these issues.

### CODE REVIEW

**Review by ddkang — COMMENTED** [review]
Can we test this?

**Comment by Vimalakirti** [comment]
> Can we test this?

we can test this with an ONNX that matches the description above

**Comment by liliatangxy** [comment]
Why can't we test this with a `testBasicBlock` test?

**Comment by Vimalakirti** [comment]
> Why can't we test this with a `testBasicBlock` test?

The files changed are all under `layer/`

**Review by liliatangxy — APPROVED** [review]

**Review by ddkang — APPROVED** [review]

**Pull request merged**
