### PR TITLE
Transpose+permute optimization for 1x1 kernel

### PR DESCRIPTION
**Pull request by liliatangxy**
Instead of using copy constraint for a 1x1 kernel, we can use transpose+permute for ch_in to be the last dimension for the matmul.

first 1x1 kernel layer in resnet50 old -> new: 932s -> 651s (-30%)

### CODE REVIEW

**Comment by Vimalakirti** [comment]
Do you have estimates on how much it could improve?

**Comment by liliatangxy** [comment]
updated the timings

**Review by Vimalakirti — COMMENTED** [review]
Seems good for me, but it looks pretty complicated. Do you think it will look better if we group all 1x1 computations together under one if block?

**Comment by liliatangxy** [comment]
I think grouping in one if might have a lot of repeated code. I added additional comments and grouped the optimization code together more, hope that helps.

**Review by Vimalakirti — APPROVED** [review]

**Review by ddkang — APPROVED** [review]

**Pull request merged**
