### PR TITLE
Optimize copy constraint

### PR DESCRIPTION
**Pull request by liliatangxy**
* avoid intermediate interpolation in multiplication
* binary tree-ordered multiplication
* precompute ssig evals

The before-and-after stats for this part for the first CCBB of resnet18 on Bing-Jyue's mac:
17668.51s -> 61.97s

### CODE REVIEW

**Comment by ddkang** [comment]
How much faster is this?

**Comment by Vimalakirti** [comment]
The mul_polys fails in `cargo test` (resolved)

**Comment by ddkang** [comment]
How much does this help by? Please put it in the PR comments for posterity

**Comment by liliatangxy** [comment]
I added it to the top comment

**Review by ddkang — APPROVED** [review]

**Pull request merged**
